FROM docker.io/kalilinux/kali-rolling:latest

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && apt-get upgrade -y && \
    apt-get install -y --no-install-recommends \
        # Reconocimiento
        nmap masscan tshark fping \
        # Enumeración Web
        ffuf gobuster nikto curl \
        # Explotación y Fuerza Bruta
        metasploit-framework sqlmap hashcat john hydra \
        # Pivoting y Túneles
        proxychains4 socat sshuttle openvpn \
        # Utilidades base
        iproute2 dnsutils iputils-ping \
        python3 python3-pip jq tmux sudo \
    && apt-get clean && rm -rf /var/lib/apt/lists/* && \
    echo "ALL ALL=(ALL) NOPASSWD: ALL" > /etc/sudoers.d/zzzz-nopasswd && \
    chmod 0440 /etc/sudoers.d/zzzz-nopasswd

WORKDIR /htb
CMD ["/bin/bash"]
