FROM registry.fedoraproject.org/fedora-toolbox:latest

# Fusión Media + Books
RUN dnf update -y && dnf install -y \
    mpd \
    beets \
    tor \
    python3-pip \
    && dnf clean all

# Configuraciones por defecto para los demonios
RUN mkdir -p ~/.tor_data ~/.config/mpd
