FROM registry.fedoraproject.org/fedora-toolbox:latest

RUN source /etc/os-release && \
    curl -fsSL \
      "https://packages.microsoft.com/config/fedora/${VERSION_ID}/packages-microsoft-prod.rpm" \
      -o /tmp/packages-microsoft-prod.rpm && \
    rpm -Uvh /tmp/packages-microsoft-prod.rpm && \
    rm -f /tmp/packages-microsoft-prod.rpm && \
    dnf install -y \
        powershell \
        krb5-workstation \
        bind-utils \
        iproute \
        jq && \
    dnf clean all && \
    rm -rf /var/cache/dnf
