FROM registry.fedoraproject.org/fedora-toolbox:latest

ENV DEBIAN_FRONTEND=noninteractive

RUN dnf -y upgrade --refresh && \
    dnf -y install --setopt=install_weak_deps=False --nodocs \
        calibre \
        tor torsocks \
        python3 python3-pip \
        wget curl git unzip p7zip p7zip-plugins && \
    dnf clean all && \
    rm -rf /var/cache/dnf
