FROM registry.fedoraproject.org/fedora-toolbox:latest

# hadolint ignore=DL4006
RUN dnf install -y \
    clinfo intel-compute-runtime libva-intel-media-driver \
    python3 zstd curl \
    oneapi-level-zero oneapi-level-zero-devel \
    ocl-icd ocl-icd-devel && \
    dnf clean all && \
    rm -rf /var/cache/dnf

RUN curl -LsSf https://astral.sh/uv/install.sh | sh

RUN /root/.local/bin/uv tool install --dir /usr/local/bin aider-chat
