FROM registry.fedoraproject.org/fedora:44

RUN dnf install -y --setopt=install_weak_deps=False \
        ansible \
        python3-pip \
        git \
        openssh-clients \
        sshpass \
        yamllint \
        ansible-lint && \
    dnf clean all

# Directorio de trabajo predeterminado para automatización de infraestructura
WORKDIR /workspace
