FROM registry.fedoraproject.org/fedora:latest

ENV container=podman
ENV DEBIAN_FRONTEND=noninteractive

RUN dnf -y upgrade --refresh && \
    dnf -y install --setopt=install_weak_deps=False --nodocs \
        nmap nmap-ncat arp-scan fping hping3 whois macchanger \
        tcpdump wireshark-cli socat netcat conntrack-tools ethtool \
        iproute bind-utils mtr lldpd \
        iftop nload bmon iperf3 \
        net-snmp-utils mosquitto \
        python3 python3-pip python3-scapy python3-requests jq tmux \
    && dnf clean all && \
    echo "ALL ALL=(ALL) NOPASSWD: ALL" > /etc/sudoers.d/zzzz-nopasswd && \
    chmod 0440 /etc/sudoers.d/zzzz-nopasswd

WORKDIR /ops
CMD ["/bin/bash"]
